// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddKey(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckAllStatuses():Promise<Record<string, string>>;

export function CheckStatus(arg1:string):Promise<string>;

export function DeleteKey(arg1:string,arg2:string):Promise<string>;

export function GetKeyValue(arg1:string,arg2:string):Promise<string>;

export function GetKeys():Promise<Record<string, Array<main.KeyEntry>>>;

export function GetMasterKeyStatus():Promise<string>;

export function GetStatuses():Promise<Record<string, string>>;

export function LoginWithMasterKey(arg1:string):Promise<string>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function SetMasterKey(arg1:string):Promise<string>;

export function UpdateKey(arg1:string,arg2:string,arg3:string):Promise<string>;
