// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddKey'](arg1, arg2, arg3);
}

export function CheckAllStatuses() {
  return window['go']['main']['App']['CheckAllStatuses']();
}

export function CheckStatus(arg1) {
  return window['go']['main']['App']['CheckStatus'](arg1);
}

export function DeleteKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteKey'](arg1, arg2);
}

export function GetKeyValue(arg1, arg2) {
  return window['go']['main']['App']['GetKeyValue'](arg1, arg2);
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}

export function GetMasterKeyStatus() {
  return window['go']['main']['App']['GetMasterKeyStatus']();
}

export function GetStatuses() {
  return window['go']['main']['App']['GetStatuses']();
}

export function LoginWithMasterKey(arg1) {
  return window['go']['main']['App']['LoginWithMasterKey'](arg1);
}

export function OnBeforeClose(arg1) {
  return window['go']['main']['App']['OnBeforeClose'](arg1);
}

export function SetMasterKey(arg1) {
  return window['go']['main']['App']['SetMasterKey'](arg1);
}

export function UpdateKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateKey'](arg1, arg2, arg3);
}
